Fixes to compile for 5.0 compute capability devices
zpzim/SCAMP pull request #49
Opened 2021-12-09 06:05 UTC by rf

The compile flags were missing for `qt_kernels` and `gpu_utils` which means any CUDA code there wasn't getting compiled for all compute capability levels. This resulted in `no kernel image` errors despite having sufficient compute capability.

In addition, in some places, `cudaPeekAtLastError` was used, which only needs to be used when launching a kernel, not when doing an operation that can actually return a value such as `cudaFree` etc.

This had resulted in getting a `no kernel image` error within the `free_mem` section, as that was where the previously mentioned issue actually surfaced.

2021-12-10 01:48 UTC, zpzim commented
First of all, thanks for taking the time to make a PR. Really appreciate it. I haven't used any Maxwell cards with this repository so this is a good catch.

I'll try to review this and have it merged ASAP.

2021-12-19 17:15 UTC, zpzim commented on src/qt_helper.cpp
> +  //
Delete

2021-12-19 17:18 UTC, zpzim requested changes
Thanks again for the PR. Looks good. Just one nit to delete an extra line.

Before we can merge this PR, please rebase this change to master and address any merge conflicts (there are unlikely to be any). I have fixed the CI suite for SCAMP so the checks will run once you have rebased.

Thanks!

2021-12-19 21:38 UTC, rf commented
Thanks for reviewing! Addressed the comment, and it looks like it should merge cleanly onto master.

2021-12-19 21:51 UTC, zpzim approved these changes

2021-12-19 23:34 UTC, merged